### ISSUE TITLE
plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [shouryashashank/Automatic_raster_classifier#1]
Please fix the metadata.txt to show links which are linked to the plugin not a generic  plugin home page

**Comment by shouryashashank** [comment]
> Please fix the metadata.txt to show links which are linked to the plugin not a generic plugin home page

Done.

**Comment by NyakudyaA** [comment]
@shouryashashank Can you also remove __pycache folder. I know it doesn't allow you upload to plugin repo but for people who need to do zip install

**Comment by shouryashashank** [comment]
> @shouryashashank Can you also remove __pycache folder. I know it doesn't allow you upload to plugin repo but for people who need to do zip install

Done. 
I apologize for the inconvenience, I am very new to qgis and committed on github before reading through the complete process  on QGIS Python Plugins Repository. I will make sure these things does not happen again.

**Comment by NyakudyaA** [comment]
No worries @shouryashashank , You need to upload a new zip with the updated homepage link. it currently still points to https://shouryashashank.github.io/. If you do not have a dedicated page just make it the same link as the repo

**Comment by shouryashashank** [comment]
> No worries @shouryashashank , You need to upload a new zip with the updated homepage link. it currently still points to https://shouryashashank.github.io/. If you do not have a dedicated page just make it the same link as the repo

Done
